version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

  laravel:
    image: webdevops/php-nginx:8.2
    container_name: laravel
    volumes:
      - C:/Users/swizzen/Desktop/jenkins:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    depends_on:
      - mysql
    ports:
      - "8082:80"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - C:/Users/swizzen/Desktop/jenkins:/app
    working_dir: /app
    command: ["composer", "install"]

volumes:
  jenkins_home:
  mysql_data:
